---
title: "Cool graphs about elevators"
author: Mike Mahoney
subtitle: "Last generated on: `r Sys.Date()`"
date: today
execute:
  freeze: true
format: 
  html: 
    echo: false
params: 
  region: "NA"
  state: "MD"
---

```{r}
#| message: false
library(elevators)

library(ggplot2)
theme_set(theme_minimal())
```

```{r}
#| message: false
#| warning: false
if (params$state == "MD") {
  elevators <- md_elevators
  
  if (!is.na(params$region) && params$region != "NA") {
    elevators <- elevators[elevators$county == params$region, ]
  }
  
  elevators <- elevators[c("equipment_capacity", "equipment_speed")]
  names(elevators) <- c("capacity_lbs", "speed_fpm")
  elevators$capacity_lbs <- as.numeric(elevators$capacity_lbs)
  elevators$speed_fpm <- as.numeric(elevators$speed_fpm)
  
} else {
  
  if (!is.na(params$region) && params$region != "NA") {
    elevators <- elevators[elevators$borough == params$region, ]
  }
  
}

if (nrow(elevators) == 0) {
  stop("No elevators were selected. Did you misspell `region`?")
}
```

```{r}
#| eval: !expr params$state == "NY"
#| results: asis

cat("## Speed over time")
```

```{r}
#| message: false
#| warning: false
#| eval: !expr params$state == "NY"
#| results: asis
elevators |> 
  ggplot(aes(approval_date, speed_fpm)) + 
  geom_point(alpha = 0.05) + 
  geom_smooth() + 
  scale_y_log10()
```

## Speed versus capacity

```{r}
#| message: false
#| warning: false
elevators |> 
  ggplot(aes(capacity_lbs, speed_fpm)) + 
  geom_point(alpha = 0.05) + 
  geom_smooth() + 
  scale_y_log10()
```

```{r}
#| eval: !expr params$state == "NY"
#| results: asis

cat("## Where in the world did all my elevators go")
```

```{r}
#| message: false
#| warning: false
#| eval: !expr params$state == "NY"
#| results: asis

elevators |> 
  ggplot(aes(latitude, longitude)) + 
  geom_point(alpha = 0.05) + 
  coord_sf()
```

