---
title: "Schedule"
description: |
  Schedule of topics for FOR 796: Machine Learning for Prediction: Concepts and Applications in R
site: distill::distill_website
---

```{r echo=FALSE}
library(dplyr)

tribble(
  ~ Week, ~ Topic, ~ Packages, ~ "Homework Assigned", 
  "1", "Prediction, Estimation, and Attribution", "None", "Assignment 1",
  "2", "Regression", "None", "Assignment 2",
  "3", "Classification", "pROC", "Assignment 3",
  "4", "Classification, continued", "", "Assignment 4",
  "5", "Decision Trees", "rpart", "None",
  "6", "Random Forests", "ranger", "Assignment 5",
  "7", "Hyperparameters and Model Tuning", "ranger, purrr", "Assignment 6",
  "8", "Gradient Boosting Machines", "gbm", "Assignment 7",
  "9", "Stochastic GBMs", "lightGBM", "Assignment 8",
  "10", "Loss Functions and Regularization", "lightGBM", "Assignment 9",
  "11-13", "Additional Topics (as time allows)", "TBA", "Assignment 10"

) %>% 
  kableExtra::kable() %>% 
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover"))
```

# Readings

Unless specified in the weekly handouts, these are not required, but may help
in understanding a week's topics. "CASI" refers to 
["Computer Age Statistical Inference"](https://web.stanford.edu/~hastie/CASI_files/PDF/casi.pdf)
while "HOML" refers to 
["Hands-on Machine Learning with R"](https://bradleyboehmke.github.io/HOML)

## Week 1

### Prediction, Estimation, and Attribution

CASI 1.0-1.1, 8.4 (just the first two pages), and Epilogue.

Breiman, Leo. 2001. Statistical Modeling: The Two Cultures Statist. Sci. 16(3) 199 - 231,  https://doi.org/10.1214/ss/1009213726 

Efron, Bradley. 2020. Prediction, Estimation, and Attribution, Journal of the American Statistical Association, 115(530), 636-655, https://doi.org/10.1080/01621459.2020.1762613 

Shmueli, Galit. 2010. To Explain or to Predict?. Statistical Science 25(3) 289-310, https://doi.org/10.1214/10-STS330 
 
## Week 2

### Regression and linear regression

HOML 1.1, 4

### Hold-out and validation sets

HOML 2.2

CASI 12.2 (first page only)

## Week 3

### Cross Validation

CASI 12

## Week 13

Mitchell, Margaret, Simone Wu, Andrew Zaldivar, Parker Barnes, Lucy Vasserman, 
Ben Hutchinson, Elena Spitzer, Inioluwa Deborah Raji, and Timnit Gebru. 2019. 
Model cards for model reporting." In Proceedings of the conference on fairness, 
accountability, and transparency, pp. 220-229. 2019. https://arxiv.org/abs/1810.03993
