---
title: "Cool graphs about elevators"
author: Mike Mahoney
subtitle: "Last generated on: `r Sys.Date()`"
date: "2022-08-05"
execute:
  freeze: true
format: 
  html: 
    echo: false
params: 
  region: "NA"
  state: "MD"
---

```{r}
#| message: false
library(elevators)

library(ggplot2)
theme_set(theme_minimal())
```

```{r}
#| message: false
#| warning: false
con <- DBI::dbConnect(RSQLite::SQLite(), "elevators.db")
query <- "SELECT 
    ?capacity_column AS capacity_lbs, 
    ?speed_column    AS speed_fpm,
    ?approval_date   AS approval_date,
    ?latitude        AS latitude, 
    ?longitude       AS longitude
  FROM ?table"

if (params$state == "NY") {
  query_args <- list(
    capacity_column = DBI::dbQuoteIdentifier(con, "capacity_lbs"),
    speed_column = DBI::dbQuoteIdentifier(con, "speed_fpm"),
    approval_date = DBI::dbQuoteIdentifier(con, "approval_date"),
    latitude = DBI::dbQuoteIdentifier(con, "latitude"),
    longitude = DBI::dbQuoteIdentifier(con, "longitude"),
    region_column = DBI::dbQuoteIdentifier(con, "borough"),
    region = params$region
  )
} else {
  query_args <- list(
    capacity_column = DBI::dbQuoteIdentifier(con, "equipment_capacity"),
    speed_column = DBI::dbQuoteIdentifier(con, "equipment_speed"),
    approval_date = 0,
    latitude = 0,
    longitude = 0,
    region_column = DBI::dbQuoteIdentifier(con, "county"),
    region = params$region
  )
}

if (!is.na(params$region) && params$region != "NA") {
  query <- paste(query, "
  WHERE 
    ?region_column == ?region")
} else {
  query_args <- head(query_args, -2)
}
  
query <- DBI::sqlInterpolate(
  con, 
  query, 
  table = DBI::dbQuoteIdentifier(con, "md_elevators"),
  .dots = query_args
)
elevators <- DBI::dbGetQuery(con, query)
elevators$capacity_lbs <- as.numeric(elevators$capacity_lbs)
elevators$speed_fpm <- as.numeric(elevators$speed_fpm)
DBI::dbDisconnect(con)
```

```{r}
#| eval: !expr params$state == "NY"
#| results: asis

cat("## Speed over time")
```

```{r}
#| message: false
#| warning: false
#| eval: !expr params$state == "NY"
#| results: asis
elevators |> 
  ggplot(aes(approval_date, speed_fpm)) + 
  geom_point(alpha = 0.05) + 
  geom_smooth() + 
  scale_y_log10()
```

## Speed versus capacity

```{r}
#| message: false
#| warning: false
elevators |> 
  ggplot(aes(capacity_lbs, speed_fpm)) + 
  geom_point(alpha = 0.05) + 
  geom_smooth() + 
  scale_y_log10()
```

```{r}
#| eval: !expr params$state == "NY"
#| results: asis

cat("## Where in the world did all my elevators go")
```

```{r}
#| message: false
#| warning: false
#| eval: !expr params$state == "NY"
#| results: asis

elevators |> 
  ggplot(aes(latitude, longitude)) + 
  geom_point(alpha = 0.05) + 
  coord_sf()
```

