---
title: "waywiser is now a part of rOpenSci"
description: "Plus version 0.3.0 now on CRAN, and a new preprint"
author:
  - name: Mike Mahoney
    url: {}
date: "2023-03-23"
categories: ["R", "waywiser", "Spatial", "Data science", "R packages"]
format: 
  html:
    toc: true
engine: knitr
---

I'm thrilled to share that [waywiser](https://docs.ropensci.org/waywiser/), my R package focused on providing framework-agnostic (but tidymodels-friendly) methods for assessing models fit to spatial data,^[I use this terminology in a number of places throughout the documentation to try and emphasize that nothing about the models themselves need to be spatial. The models don't need to incorporate spatial information at all for these methods to be useful. I'll admit that it's a bit clunky, though, and have a habit of lapsing back to "spatial models".] has passed peer review and been accepted to [rOpenSci](https://ropensci.org/). As always, [the review process](https://github.com/ropensci/software-review/issues/571) improved the package immensely, thanks to the thoughtful reviews of [Virgilio Gómez-Rubio](https://becarioprecario.github.io/) and [Jakub Nowosad](https://jakubnowosad.com/),^[Only a little intimidating having my package reviewed by the authors of two of the best books on using R for spatial analysis!] as well as the shepherding of [Anna Krystalli](https://www.r-rse.eu/) and [Paula Moraga](https://www.paulamoraga.com/) as editors.

As of Monday, the reviewed version has officially [made its way to CRAN](https://cran.r-project.org/package=waywiser). This is a [huge update](https://docs.ropensci.org/waywiser/news/index.html#waywiser-030), bringing in a ton of new functions and improving consistency and speed across the package, and I'm excited to have it officially released.

I'm also very excited to have put out a [preprint describing the package](https://arxiv.org/abs/2303.11312), which goes a bit deeper into the logic of why and how the package implements the features it does. This is my first solo-authored paper,^[And frankly, I don't intend to make it a habit. I highly appreciate working with collaborators, particularly with my current research group, and know that my work is usually better for having gone through multiple rounds of revisions before being released. I really missed that process while working on this paper!] and by far and away the one with the most equations.^[23 numbered equations! My undergraduate degree is in ecology, where [each additional equation per page is associated with 28% fewer citations](https://www.pnas.org/doi/abs/10.1073/pnas.1205259109); four years ago I'd never have expected I'd be writing a paper that looks like this] Despite both of those, I'm pretty pleased with how this paper turned out; I think it's a useful addition to the package documentation for users who want a more thorough explication of the scholarly background of package features.
