---
title: "Introduction to Data Science"
output: html_document
---

## Week One:

This week we'll start to get familiar with R, and learn how to make visually 
appealing graphs using the `ggplot2` package.

### Due This Week

* Monday: Install R, R Studio, and the tidyverse -- [follow the instructions in R4DS Section 1.1 -> 1.6](https://r4ds.had.co.nz/introduction.html)

### Readings

#### Required

* Monday: [R4DS Section 1.1 -> 1.6](https://r4ds.had.co.nz/introduction.html)
    * Make sure you follow the instructions to install R, R Studio, and the 
      tidyverse!
* Wednesday: [R4DS Section 3.1 -> 3.6](https://r4ds.had.co.nz/data-visualisation.html)
    * Code through it!
* Friday: [ggplot2 cheatsheet](https://rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf)

#### Optional

* [What is Code?](https://www.bloomberg.com/graphics/2015-paul-ford-what-is-code/)
    * Sections 1 through 5 are great for understanding this class. The rest is 
      great for understanding our world. This is super long -- I want to 
      empahsize that this one is definitely optional, but it's the best article 
      I've ever read about programming.
* [The R Graphics Cookbook](https://r-graphics.org/)
    * This book is a good reference if you're just looking for a guide on how 
      you'd make a specific _type_ of plot.

### Slides

* [Intro to the Course and Plotting](01/01-intro-plotting.html)

### Student Work

* [Homework 01](01/01-hw.Rmd)
    * Due: Monday of Week Two

<hr>

## Week Two:

This week we'll start talking about data -- how R views data, how R stores data
in objects, and how we can get our data back out of it.

### Due This Week:

* Monday: [Homework 01](01/01-hw.Rmd)

### Readings

#### Required

* Monday: [Adv R Chapter 3.2](https://adv-r.hadley.nz/vectors-chap.html)
* Wednesday: [Adv R Chapter 3.5 & 3.6](https://adv-r.hadley.nz/vectors-chap.html)
* Friday: [Adv R Chapter 4.1 -> 4.4](https://adv-r.hadley.nz/subsetting.html)
* For all of these, practice by coding alongside the text. Don't worry about 
  doing the exercises; they're designed for people with a more advanced 
  knowledge of R.

#### Optional

* [Tidy Data](https://vita.had.co.nz/papers/tidy-data.pdf), the paper that 
  started it all
  
### Slides

* [Introduction to Data](02/02-data.html)

### Student Work

* [Homework 02](02/02-hw.Rmd)
    * Due: Monday of Week 
    
<hr>

## Week Three:

This week we'll introduce data wrangling, using functions from the `dplyr` 
package to filter and transform our data.

### Due This Week:

* Monday: [Homework 02](02/02-hw.Rmd)

### Readings

#### Required

* Monday: [R4DS: Chapter 5](https://r4ds.had.co.nz/transform.html)
    * Code through it!
* Wednesday: [dplyr cheatsheet](https://github.com/rstudio/cheatsheets/raw/master/data-transformation.pdf)

#### Optional

### Slides

### Student Work

<hr>

## Week Four:

This week we'll go over loading and exporting data from R, transform our data 
using `tidyr`, and work on putting the packages we've been using together. On 
the way, we'll talk about naming things and the joys of the `here` package.

### Due This Week:

### Readings

#### Required

#### Optional

### Slides

### Student Work

<hr>

## Week ABCDEFGH:

### Due This Week:

### Readings

#### Required

#### Optional

### Slides

### Student Work

<hr>

tidyr: https://kbroman.org/dataorg/ ; https://r4ds.had.co.nz/tidy-data.html

R markdown: https://rmd4sci.njtierney.com/why-rmarkdown.html

https://arxiv.org/pdf/1903.07639.pdf